#!/usr/local/bin/bash

exec 2>&1

TMP=/tmp
WORK="$TMP/$$"
# Split the encoded data into name=value pairs
BASE=/usr/local/www/apache24/cgi-data
OPTS="`echo $QUERY_STRING | tr \& "\n" | grep =`"

mkdir -p $WORK

echo "Content-type: text/html; charset=iso-8859-1"
echo
# Decode the form data
for opt in $OPTS; do
   NAME=`echo $opt | sed 's/=/ /g' | awk '{print $1}'`
   VALUE="`echo $opt | sed 's/=/ /g' | awk '{print $2}' | \
          sed 's,%,\\\x,g' | \
          sed 's~\\\x2C~,~g' | \
          sed 's/+/ /g'`"
   if echo "$NAME" | grep -q ^DEV ; then
      LIGHTCNT=$(cat $BASE/lights.dat | wc -l | tr -d " \t")
echo ":$LIGHTCNT:<BR>"
      tail -$LIGHTCNT /tmp/lights.log | tr : " " | while read TIME COL STATE LIGHT; do
        if [ "$VALUE" = "$LIGHT" ] ; then
          echo $STATE
        fi
      done
   fi
done
rm -r $WORK
