#!/usr/local/bin/bash

exec 2>&1

TMP=/tmp
BASE="/usr/local/media/Audio"
FILES="`cd $BASE ; find ./ -type f -name '*[mM][pP]3' | sort -f | tr \  '^'`"
CACHE=$TMP/.musiccache

find $BASE -type f -name '*[mM][pP]3' | sort -f | cut -d / -f 5- | while read FPATH ; do
  FLDR=`dirname "$FPATH"`
  PARENT=`basename "$FLDR"`
  FNAME=`basename "$FPATH"`
  VALUE=$(echo $FPATH | tr \  '^' | sed -e s/\'/%27/g)
  echo "<OPTION VALUE='$VALUE'> $PARENT - $FNAME" 
done > $CACHE.new

mv $CACHE.new $CACHE
