#!/usr/local/bin/bash

exec 2>&1

TMP=/tmp
BASE="/usr/local/Audio/Music"
CACHE=$TMP/.musiccache2

  echo "Finding songs"
  rm $CACHE.new ; touch $CACHE.new
  cd $BASE 
  find ./ -type f -name '*[mM][pP]3' | while read FPATH ; do
    PARENT=""
    FPFIX="`echo $FPATH | sed -e s/\'/%27/g -e 's/ /^/g'`"
    for FN in `echo $FPFIX | tr / \ ` ; do 
      FNAME="`echo $FN | tr '^' \ | sed -e s/\'/%27/g`" 
      PARENT="$CURRENT"
      CURRENT="$FNAME"
    done
    [ "$OP" = "$PARENT" ] || printf "."
    OP="$PARENT"
    echo "<OPTION VALUE='$FPFIX'> $PARENT - $CURRENT" >> $CACHE.new
  done

cat $CACHE.new | sort -k 3 >$CACHE 
rm -f $CACHE.new
