#!/usr/local/bin/bash

exec 2>&1

renice 20 $$

PATH="$PATH:/usr/local/bin"
TMP=/tmp
WORK="$TMP/$$"
export HOME=$WORK
# Split the encoded data into name=value pairs
MDPT="None"
mdconfig -l | while read MDEV; do 
  if mdconfig -l -u $MDEV | grep -q iso$ ; then
    MDPT=$MDEV
    MOUNTED=`mount | grep /dev/$MDPT | awk '{print $3}' | tail -1`
    MOUNTDEV=`mount | grep /dev/$MDPT | awk '{print $1}' | tail -1`
  fi
done
mkdir -p $WORK

echo "Content-type: text/html; charset=iso-8859-1"
echo
echo "<HTML><HEAD><TITLE>$TITLE</TITLE>"
echo "</HEAD>"
echo "<BODY>"

#echo "<H3>`whoami`  $MOUNTED $MOUNTDEV</H3>"
# Decode the form data
OPTS=`cat - | tr \& "\n"`
for opt in $OPTS; do
   NAME=`echo $opt | sed 's/=/ /g' | awk '{print $1}'`
   VALUE="`echo $opt | sed 's/=/ /g' | awk '{print $2}' | \
          sed 's/+/ /g' | \
          sed 's/%28/(/g' | \
          sed 's/%29/)/g' | \
          sed 's/%2C/,/g' | \
          sed 's/%2F/\//g'`"
   eval "$NAME=\"$VALUE\"" 2>&1 >/dev/null
   echo "$NAME=$VALUE<BR>"
done
#[ -f "$MOUNTME" ] || echo "Not a file:$MOUNTME:<BR>"
#[ -d "$MOUNTLOC" ] || echo "Not a folder:$MOUNTLOC:<BR>"
if [ -f "$MOUNTME" ] && [ -d "$MOUNTLOC" ] ; then
  if [ -n "$MOUNTED" ] ; then 
    sudo umount "$MOUNTED"
    sudo rmdir "$MOUNTED"
    sudo mdconfig -d -u "$MOUNTDEV"
  fi

  MDEV=`sudo mdconfig -a -t vnode -f "$MOUNTME"`
  sudo mkdir -p "$MOUNTLOC/mnt"
  sudo chmod 777 "$MOUNTLOC/mnt"
  sudo chown www:www "$MOUNTLOC/mnt"
  sudo mount_cd9660 -r "/dev/$MDEV" "$MOUNTLOC/mnt"
  MOUNTDEV="$MDEV"
  MOUNTED="$MOUNTLOC/mnt"
fi

[ -e "$MOUNTDEV" ] || MOUNTDEV="md0"

echo "<H1>Mount ISO</H1>"
echo "<FORM METHOD='POST'>"

echo "<H2>Mount file</H2>"
echo "<SELECT NAME='MOUNTME'>"
#sudo find /usr/local/ -name "*.[iI][sS][oO]" | while read MNTOPT ; do
sudo find /storage -name "*.[iI][sS][oO]" | while read MNTOPT ; do
  echo -n "<OPTION"
  echo $MDPT | grep -q "$MNTOPT" && echo -n " selected"
  echo " VALUE='$MNTOPT'>$MNTOPT</OPTION>"
done
echo "</SELECT><BR>"

echo "<H2>Mount where</H2>"
echo "<SELECT NAME='MOUNTLOC'>"
grep path\ = /usr/local/etc/smb.conf | awk '{print $3}' | sort | uniq | while read MOUNTPT ; do
  echo -n "<OPTION"
  echo $MOUNTED | grep -q "$MOUNTPT" && echo -n " selected"
  echo " VALUE='$MOUNTPT'>$MOUNTPT</OPTION>"
done
echo "</SELECT><BR>"

echo "<INPUT TYPE='SUBMIT'>"
echo "</FORM>"
echo "</BODY></HTML>"

rm -r $WORK

