#!/usr/local/bin/bash

exec 2>&1

#contants
BASE=/usr/local/www/apache24/cgi-data
OFFSET=3
HOUSECODE=i
RPT="-r 5"
BR="/usr/local/bin/br -x /dev/cuau0 -c $HOUSECODE $RPT"
SEP=","

#presets
DEVFILE="$BASE/lights.dat"
[ -f "$DEVFILE" ] || exit 1
DEVCNT=`cat $DEVFILE | wc -l`
HR=`date '+%H'`
HR=`expr $HR + $OFFSET`

echo "Content-type: text/html; charset=iso-8859-1"
echo 'cache-control: no-store'
#echo 'cache-control: max-age=300'
echo
echo "<HTML><HEAD><TITLE>$TITLE</TITLE>"
echo "</HEAD>"
echo "<BODY>"
echo "<FONT SIZE='1'>"

# Decode the form data
echo "<OL>"
# Split the encoded data into name=value pairs
OPTS=`cat - | sed 's/&/ /g'`
for opt in $OPTS; do
   NAME=`echo $opt | sed 's/=/ /g' | awk '{print $1}'`
   VALUE="`echo $opt | sed 's/=/ /g' | awk '{print $2}' | \
          sed 's,%,\\\x,g' | \
          sed 's~\\\x2C~,~g' | \
          sed 's/+/ /g'`"
#   printf "<LI><B>$NAME:</B>:$VALUE:"
   eval "$NAME=\"$VALUE\""
done

if [ -n "$DEVLIST" ] ; then
  for DEVID in $DEVLIST ; do
    echo -n "${DEVID}${SEP}"
    eval "echo -n \"\$DEV_${DEVID}_DESC${SEP}\""
    for HR in 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 ; do
      eval "echo -n \"\$DEV_${DEVID}_${HR}$SEP\""
    done
    echo ""
  done >$DEVFILE
fi

echo "</OL>"

echo "<FORM METHOD='POST'>"
echo "<TABLE BORDER='2'>"
THISDEV=0
DEVLIST=""
#while [ $THISDEV -le $DEVCNT ] ; do
for THISDEVID in 0 $(cat $DEVFILE  | cut -d , -f 1); do
  echo "<TR>"
  if [ $THISDEVID -eq 0 ] ; then
    echo "<TH>Description</TH><TH>Id</TH>"
  else
    THISLN=`cat $DEVFILE | head -$THISDEV | tail -1`
    #THISDEVID=`echo $THISLN | cut -f 1 -d $SEP`
    THISDEVDESC=`echo $THISLN | cut -f 2 -d $SEP`
    echo "<TD><INPUT TYPE='TEXT' NAME='DEV_${THISDEVID}_DESC' VALUE='$THISDEVDESC'></TD><TD>$THISDEVID</TD>"
    DEVLIST="$DEVLIST $THISDEVID"
  fi
  HR=3
  for TM in 12a 01a 02a 03a 04a 05a 06a 07a 08a 09a 10a 11a 12p 01p 02p 03p 04p 05p 06p 07p 08p 09p 10p 11p ; do
    DCNUM=`expr $HR - 15 | tr -d "-"`
    DCNUM=`expr 12 - $DCNUM`
    TXCOL="white"
    [ $DCNUM -gt 6 ] && TXCOL="black"
    DCNUM=`expr 15 + 20 "*" $DCNUM`
    BPT=`expr 255 - $DCNUM`
    HXNUM=`printf "%02X" ${DCNUM}`
    HXBPT=`printf "%02X" ${BPT}`
    if [ "$THISDEVID" = "0" ] ; then
      echo "<TH STYLE=\"color:$TXCOL;background-color:#$HXNUM${HXNUM}${HXBPT};\">$TM</TH>"
    else
      THISDEVTMSET=`echo $THISLN | cut -f $HR -d $SEP`
      DCNUM=`expr 128 + $DCNUM / 2`
      HXNUM=`printf "%02X" ${DCNUM}`
      if [ "$THISDEVTMSET" = "On" ] ; then 
        OPTON="CHECKED='TRUE'"
        OPTOF=""
        TDSTYLE="background-color:#00${HXNUM}00;"
      else
        OPTON=""
        OPTOF="CHECKED='checked'"
        TDSTYLE="background-color:#${HXNUM}0000;"
      fi
      #echo "<TD><SELECT NAME='DEV_${THISDEVID}_${HR}'><OPTION $OPTON>On</OPTION><OPTION $OPTOF>Off</OPTION></SELECT></TD>"
      echo "<TD STYLE=\"$TDSTYLE\"><INPUT TYPE='RADIO' NAME='DEV_${THISDEVID}_${HR}' VALUE='On' $OPTON ><BR><INPUT TYPE='RADIO' NAME='DEV_${THISDEVID}_${HR}' VALUE='Off' $OPTOF ></TD>"
    fi
    HR=`expr $HR + 1`
  done
  THISDEV=`expr $THISDEV + 1`
  echo "</TR>"
done
echo "</TABLE>"
echo "<INPUT TYPE='HIDDEN' NAME='DEVLIST' VALUE='$DEVLIST'>"
echo "<INPUT TYPE='SUBMIT'>"
echo "</FORM>"
echo "</BODY></HTML>"

