#!/usr/local/bin/bash

exec 2>&1

TMP=/tmp
BASE="/usr/local/Audio/Music"
FILES="`cd $BASE ; find ./ -type f -name '*[mM][pP]3' | sort -f | tr \  '^'`"
WORK="$TMP/$$"
CACHE=$TMP/.musiccache
export HOME=$WORK
PLAYLIST=$WORK/trax.txt
MPG123LOG="$TMP/mpg123.log"
ISPLAYING=1
ps wwaux | grep -v grep | grep -q mpg123 && ISPLAYING=0
if [ -f $MPG123LOG ] ; then 
  TITLE="`grep Playing $MPG123LOG | tail -1 | cut -b 26-`"
else
  TITLE="Not playing anything"
fi

echo "Content-type: text/html; charset=iso-8859-1"
echo
echo "<HTML><HEAD>"
echo "<TITLE>$TITLE</TITLE>"
if [ "$ISPLAYING" = "0" ] ; then
  echo "<meta http-equiv='Refresh' content='15; url=/cgi-bin/monitor'>"
else
  echo "<meta http-equiv='Refresh' content='1; url=/cgi-bin/music'>"
fi
echo "</HEAD>"
echo "<BODY>"
echo "<PRE>"
[ -f $MPG123LOG ] && tail -20 $MPG123LOG
echo "</PRE>"
echo "<A HREF='/cgi-bin/music'>Change</A> the playlist."
echo "</BODY></HTML>"

