#!/usr/local/bin/bash

exec 2>&1

getlock() {
 LOCKFILE=/tmp/br.lock
 LOCKWAIT=20
 while [ -f $LOCKFILE ] ;  do
  sleep $LOCKWAIT
  LOCKWAIT=`expr $LOCKWAIT - 1`
  [ $LOCKWAIT -eq 0 ] && exit 0
 done
 touch $LOCKFILE
}

droplock() { 
 LOCKFILE=/tmp/br.lock
 rm -f $LOCKFILE
}

ROUTER=16

reset_router() {
      getlock
      echo "Resetting router at `date '+%Y%m%d %H:%M:%S'`" >>/tmp/router.txt
      eval "/usr/local/bin/br -x /dev/cuau0 -c i -f $ROUTER" 
      sleep 10
      eval "/usr/local/bin/br -x /dev/cuau0 -c i -n $ROUTER" 
      sleep 10
      eval "/usr/local/bin/br -x /dev/cuau0 -c i -n $ROUTER" 
      sleep 10
      eval "/usr/local/bin/br -x /dev/cuau0 -c i -n $ROUTER" 
      droplock
}


ANYPING="no"
for SITE in www.google.com www.yahoo.com www.claytontucker.com ; do
  ping -qc 5 $SITE 2>/dev/null >/dev/null && ANYPING="yes"
done

[ "$ANYPING" = "no" ] && reset_router

