#!/usr/local/bin/bash

exec 2>&1

TMP=/tmp
WORK="$TMP/$$"
# Split the encoded data into name=value pairs
#OPTS=`cat - | sed 's/&/ /g'`
OPTS="`echo $QUERY_STRING | tr \& "\n" | grep =`"
DEVS="`mixer | grep -v source | cut -f 2 -d \ `"

mkdir -p $WORK

echo "Content-type: text/html; charset=iso-8859-1"
echo
echo "<HTML><HEAD><TITLE>SetOneMixerDevice</TITLE>"
echo "</HEAD>"
echo "<BODY>"
# Decode the form data
for opt in $OPTS; do
   NAME=`echo $opt | sed 's/=/ /g' | awk '{print $1}'`
   VALUE="`echo $opt | sed 's/=/ /g' | awk '{print $2}' | \
          sed 's,%,\\\x,g' | \
          sed 's~\\\x2C~,~g' | \
          sed 's/+/ /g'`"
#   printf "<LI><B>$NAME:</B>:$VALUE:"
   if echo "$NAME" | grep -q ^DEV ; then
      DV="`echo $NAME | cut -b 4-`"
#      echo "<BR>/usr/sbin/mixer $DV $VALUE:$VALUE <BR>" 
      eval "/usr/sbin/mixer $DV $VALUE:$VALUE" 
   fi
   if echo "$NAME" | grep -q ^LIST ; then
     echo "$DEVS"
     echo "."
   fi
done
#echo $OPTS
rm -r $WORK
echo "</BODY></HTML>"
